// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC19IqggNF5JeojjPMhRFs3UtoFXBzemg',
    appId: '1:302241108574:android:8bd12b59f48dd407f25acf',
    messagingSenderId: '302241108574',
    projectId: 'opsmate-85c7a',
    storageBucket: 'opsmate-85c7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC41q6FdGPm3FHAe4CP-S0x0gdjlisDVCA',
    appId: '1:302241108574:ios:42c4aa801b21490af25acf',
    messagingSenderId: '302241108574',
    projectId: 'opsmate-85c7a',
    storageBucket: 'opsmate-85c7a.firebasestorage.app',
    androidClientId: '302241108574-44gvun50ql0r0urrlkg71p389lofe2jn.apps.googleusercontent.com',
    iosClientId: '302241108574-fe4k882kqc9cj02afk73nfpi8qioce3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.opsmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC41q6FdGPm3FHAe4CP-S0x0gdjlisDVCA',
    appId: '1:302241108574:ios:42c4aa801b21490af25acf',
    messagingSenderId: '302241108574',
    projectId: 'opsmate-85c7a',
    storageBucket: 'opsmate-85c7a.firebasestorage.app',
    androidClientId: '302241108574-44gvun50ql0r0urrlkg71p389lofe2jn.apps.googleusercontent.com',
    iosClientId: '302241108574-fe4k882kqc9cj02afk73nfpi8qioce3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.opsmate',
  );
}
